# TOTO予定データの取得

[001](001_データ収集.ipynb)/[002](002_データ加工.ipynb)は過去のデータの収集をしてきたが、予想の対象となるデータを見ていく。

TOTOは年毎に〇回目という通し番号を振りなおしておらず、URLで`holdCntId=X`でX回目の開催データが得られる。  
開催ではTOTO,Mini TOTO,TOTO Goalの3種があるが、必ずすべて開催されるわけではない。

In [1]:
import pandas as pd

def _process_frame(tmp):
    return tmp[1:].drop(0,axis=1).drop(5,axis=1).rename(columns={1:tmp[1][0],2:tmp[2][0],3:tmp[3][0],4:"ホーム",6:"アウェイ"})

holdCntId = 200
url = "http://sport-kuji.toto-dream.com/dci/I/IPA/IPA01.do?op=disptotoLotInfo&holdCntId=%04d" % holdCntId
dfs = pd.io.html.read_html(url)
if len(dfs) is 20 or 24:
    print("ALL")
    tmp = dfs[3]
    if len(tmp) is 14:   # TOTO
        toto_df = _process_frame(tmp)
        print("TOTO")
        display(toto_df)
    tmp = dfs[8 + 1 if len(dfs) is 24 else 0]
    if len(tmp) is 6:    # Mini TOTO A
        minitoto_df_A = _process_frame(tmp)
        print("Mini TOTO")
        display(minitoto_df_A)
    tmp = dfs[13 + 2 if len(dfs) is 24 else 0]
    if len(tmp) is 6:   # Mini TOTO B
        minitoto_df_B = _process_frame(tmp)
        print("Mini TOTO")
        display(minitoto_df_B)
    tmp = dfs[18 + 3 if len(dfs) is 24 else 0]
    if len(tmp) is 4:   # TOTO GOAL
        totogoal_df = _process_frame(tmp)
        print("TOTO GOAL")
        display(totogoal_df)
elif len(dfs) is 18:       # Mini TOTO(A,B) & TOTO GOAL
    print("mini2 + goal")
    if len(dfs[3]) is 6:    # Mini TOTO A
        minitoto_df_A = _process_frame(tmp)
        print("Mini TOTO")
        display(minitoto_df_A)
    if len(dfs[9]) is 6:   # Mini TOTO B
        minitoto_df_B = _process_frame(tmp)
        print("Mini TOTO")
        display(minitoto_df_B)
    if len(dfs[15]) is 4:   # TOTO GOAL
        totogoal_df = _process_frame(tmp)
        print("TOTO GOAL")
        display(totogoal_df)
elif len(dfs) is 12:       # Mini TOTO & TOTO GOAL
    print("mini + goal")
    if len(dfs[3]) is 6:    # Mini TOTO A
        minitoto_df_A = _process_frame(tmp)
        print("Mini TOTO")
        display(minitoto_df_A)
    if len(dfs[9]) is 4:   # TOTO GOAL
        totogoal_df = _process_frame(tmp)
        print("TOTO GOAL")
        display(totogoal_df)    
elif len(dfs) is 6:   # TOTO GOALのみの場合
    print("goal")
    if len(dfs[3]) is 4:
        totogoal_df = _process_frame(tmp)
        print("TOTO GOAL")
        display(totogoal_df)

ALL
TOTO

      開催日 試合開始予定時間   競技場          ホーム       アウェイ
1   03/18    14:00   味スタ         ＦＣ東京    清水エスパルス
2   03/18    14:00   ヤマハ       ジュビロ磐田  京都パープルサンガ
3   03/18    14:00   広島ビ    サンフレッチェ広島      浦和レッズ
4   03/18    15:30   豊田ス  名古屋グランパスエイト   鹿島アントラーズ
5   03/18    16:00  フクアリ  ジェフユナイテッド千葉     アビスパ福岡
6   03/18    15:00    埼玉    大宮アルディージャ  アルビレックス新潟
7   03/18    15:00    小瀬    ヴァンフォーレ甲府   川崎フロンターレ
8   03/18    16:00   日産ス    横浜 Ｆ・マリノス     セレッソ大阪
9   03/18    19:00    万博        ガンバ大阪    大分トリニータ
10  03/18    14:00    鳥栖        サガン鳥栖    ヴィッセル神戸
11  03/18    14:00  ユアスタ       ベガルタ仙台      柏レイソル
12  03/18    14:00   山形県     モンテディオ山形   コンサドーレ札幌
13  03/18    14:00    駒沢  東京ヴェルディ１９６９       愛媛ＦＣ

Mini TOTO

     開催日 試合開始予定時間   競技場          ホーム       アウェイ
1  03/18    14:00   味スタ         ＦＣ東京    清水エスパルス
2  03/18    14:00   ヤマハ       ジュビロ磐田  京都パープルサンガ
3  03/18    14:00   広島ビ    サンフレッチェ広島      浦和レッズ
4  03/18    15:30   豊田ス  名古屋グランパスエイト   鹿島アントラーズ
5  03/18    16:00  フクアリ  ジェフユナイテッド千葉     アビスパ福岡

Mini TOTO

     開催日 試合開始予定時間  競技場        ホーム       アウェイ
1  03/18    15:00   埼玉  大宮アルディージャ  アルビレックス新潟
2  03/18    15:00   小瀬  ヴァンフォーレ甲府   川崎フロンターレ
3  03/18    16:00  日産ス  横浜 Ｆ・マリノス     セレッソ大阪
4  03/18    19:00   万博      ガンバ大阪    大分トリニータ
5  03/18    14:00   鳥栖      サガン鳥栖    ヴィッセル神戸

TOTO GOAL

     開催日 試合開始予定時間   競技場          ホーム      アウェイ
1  03/18    16:00  フクアリ  ジェフユナイテッド千葉    アビスパ福岡
2  03/18    15:00    小瀬    ヴァンフォーレ甲府  川崎フロンターレ
3  03/18    19:00    万博        ガンバ大阪   大分トリニータ

無関係なフレームが多いが、とりたいデータは開催日/試合開始予定時間/競技場/ホーム/アウェイのデータである。  
開催日が含まれるデータのみ収集してみる。

In [2]:
holdCntId = 1042
url = "http://sport-kuji.toto-dream.com/dci/I/IPA/IPA01.do?op=disptotoLotInfo&holdCntId=%04d" % holdCntId
dfs = pd.io.html.read_html(url)

In [3]:
for df in dfs:
    if df[1][0]=="開催日":
        if len(df)==14:
            print("TOTO")
            display(df)
        elif len(df) == 6:
            print("Mini TOTO")
            display(df)
        elif len(df) == 4:
            print("TOTO Goal")
            display(df)

TOTO

       0      1         2     3                4    5            6
0    NaN    開催日  試合開始予定時間   競技場  指定試合（ホームvsアウェイ）  NaN          NaN
1    1.0  09/15     14:00  ユアスタ           ベガルタ仙台   VS         ＦＣ東京
2    2.0  09/15     18:00  パロ瑞穂         名古屋グランパス   VS    Ｖ・ファーレン長崎
3    3.0  09/15     19:00  ノエスタ          ヴィッセル神戸   VS        ガンバ大阪
4    4.0  09/15     19:00  三協Ｆ柏            柏レイソル   VS      清水エスパルス
5    5.0  09/15     19:00   等々力         川崎フロンターレ   VS  北海道コンサドーレ札幌
6    6.0  09/15     17:00  ベアスタ            サガン鳥栖   VS    サンフレッチェ広島
7    7.0  09/16     16:00   日産ス        横浜 Ｆ・マリノス   VS        浦和レッズ
8    8.0  09/15     18:00   熊谷陸        大宮アルディージャ   VS     ＦＣ町田ゼルビア
9    9.0  09/16     16:00   味スタ          東京ヴェルディ   VS       ロアッソ熊本
10  10.0  09/15     19:00  デンカＳ        アルビレックス新潟   VS      ツエーゲン金沢
11  11.0  09/15     19:00  鳴門大塚         徳島ヴォルティス   VS         ＦＣ岐阜
12  12.0  09/15     19:00  ＮＤスタ         モンテディオ山形   VS    ヴァンフォーレ甲府
13  13.0  09/16     14:00  ニッパツ             横浜ＦＣ   VS    水戸ホーリーホック

Mini TOTO

     0      1         2     3                4    5            6
0  NaN    開催日  試合開始予定時間   競技場  指定試合（ホームvsアウェイ）  NaN          NaN
1  1.0  09/15     14:00  ユアスタ           ベガルタ仙台   VS         ＦＣ東京
2  2.0  09/15     18:00  パロ瑞穂         名古屋グランパス   VS    Ｖ・ファーレン長崎
3  3.0  09/15     19:00  ノエスタ          ヴィッセル神戸   VS        ガンバ大阪
4  4.0  09/15     19:00  三協Ｆ柏            柏レイソル   VS      清水エスパルス
5  5.0  09/15     19:00   等々力         川崎フロンターレ   VS  北海道コンサドーレ札幌

Mini TOTO

     0      1         2     3                4    5          6
0  NaN    開催日  試合開始予定時間   競技場  指定試合（ホームvsアウェイ）  NaN        NaN
1  1.0  09/15     17:00  ベアスタ            サガン鳥栖   VS  サンフレッチェ広島
2  2.0  09/16     16:00   日産ス        横浜 Ｆ・マリノス   VS      浦和レッズ
3  3.0  09/15     18:00   熊谷陸        大宮アルディージャ   VS   ＦＣ町田ゼルビア
4  4.0  09/16     16:00   味スタ          東京ヴェルディ   VS     ロアッソ熊本
5  5.0  09/15     19:00  デンカＳ        アルビレックス新潟   VS    ツエーゲン金沢

TOTO Goal

     0      1         2     3                4    5          6
0  NaN    開催日  試合開始予定時間   競技場  指定試合（ホームvsアウェイ）  NaN        NaN
1  1.0  09/15     14:00  ユアスタ           ベガルタ仙台   VS       ＦＣ東京
2  2.0  09/15     18:00  パロ瑞穂         名古屋グランパス   VS  Ｖ・ファーレン長崎
3  3.0  09/15     19:00  ノエスタ          ヴィッセル神戸   VS      ガンバ大阪

一通り取れそうなので、これを関数化した。

In [4]:
def get_toto_schedule(holdCntId):
    """
    TOTOの対象ゲームを収集
    引数として開催回を指定する
    """
    toto = None
    miniA = None
    miniB = None
    goal = None
    url = "http://sport-kuji.toto-dream.com/dci/I/IPA/IPA01.do?op=disptotoLotInfo&holdCntId=%04d" % holdCntId
    dfs = pd.io.html.read_html(url)
    for df in dfs:
        if len(df)>=4 and df[1][0]=="開催日":
            if len(df)==14:
                toto = _process_frame(df)
            elif len(df) == 6:
                if miniA is None:
                    miniA = _process_frame(df)
                else:
                    miniB = _process_frame(df)
            elif len(df) == 4:
                goal = _process_frame(df)
    return toto, miniA, miniB, goal

In [5]:
toto, miniA, miniB, goal = get_toto_schedule(1043)
#display(miniB)

# TOTOの結果を集める

## 公式記録データと合わせた形に変換する

### チーム名変換DB

チーム名は「川崎フロンターレ」のように省略されていないので、これを変換するDBを作る。

まずデータを収集する。

In [6]:
from tqdm import tqdm_notebook as tqdm
data = pd.DataFrame()
for i in tqdm(range(900,1049)):
    toto, miniA, miniB, goal = get_toto_schedule(i)
    if toto is not None:
        data = pd.concat([data, toto])
    if miniA is not None:
        data = pd.concat([data, miniA])
    if miniB is not None:
        data = pd.concat([data, miniB])
    if goal is not None:
        data = pd.concat([data, goal])

HBox(children=(IntProgress(value=0, max=149), HTML(value='')))

In [7]:
import re

team_list = []
teams = pd.concat([data["ホーム"],data["アウェイ"]]).drop_duplicates()
# 漢字を含まないチーム名を削除
for team in teams:
    if re.search('[一-鿐]', team) is not None:
        team_list.append(team)
# 国名を削除
team_list.remove("日本")
team_list.remove("韓国")
team_list.remove("中国")
team_list.remove("フェロー諸島")

In [8]:
team_list

['横浜 Ｆ・マリノス',
 '鹿島アントラーズ',
 'サンフレッチェ広島',
 '清水エスパルス',
 'サガン鳥栖',
 'ベガルタ仙台',
 'セレッソ大阪',
 '大宮アルディージャ',
 'ガンバ大阪',
 '愛媛ＦＣ',
 'アビスパ福岡',
 '横浜ＦＣ',
 '名古屋グランパス',
 '浦和レッズ',
 'ヴァンフォーレ甲府',
 'ＦＣ東京',
 'ジュビロ磐田',
 'ヴィッセル神戸',
 '柏レイソル',
 '川崎フロンターレ',
 'レノファ山口ＦＣ',
 '京都サンガF.C.',
 '北海道コンサドーレ札幌',
 'アルビレックス新潟',
 'ジェフユナイテッド千葉',
 '東京ヴェルディ',
 'ツエーゲン金沢',
 'ロアッソ熊本',
 'カマタマーレ讃岐',
 'ＦＣ町田ゼルビア',
 'ファジアーノ岡山',
 '水戸ホーリーホック',
 '湘南ベルマーレ',
 '松本山雅ＦＣ',
 'モンテディオ山形',
 'ザスパクサツ群馬',
 '栃木ＳＣ',
 'アスルクラロ沼津',
 'Ｖ・ファーレン長崎',
 'ＦＣ岐阜',
 '大分トリニータ',
 '徳島ヴォルティス',
 '鹿児島ユナイテッドＦＣ',
 'ブラウブリッツ秋田',
 'ＦＣ琉球',
 'ＳＣ相模原',
 'カターレ富山',
 'ギラヴァンツ北九州',
 'ＡＣ長野パルセイロ',
 'ガイナーレ鳥取',
 '福島ユナイテッドＦＣ',
 '藤枝ＭＹＦＣ',
 'グルージャ盛岡',
 'Ｙ．Ｓ．Ｃ．Ｃ．横浜']

In [9]:
# 公式記録のデータを集める
import download
import process_data
df = download.get_db_data()
df = process_data.processing_data(df)
teams = df["ホーム"].drop_duplicates().reset_index(drop=True)
display(teams)

0       鹿島
1      名古屋
2       浦和
3      Ｇ大阪
4       広島
5       清水
6      横浜Ｆ
7     横浜FM
8      東京Ｖ
9       千葉
10      磐田
11      湘南
12       柏
13     Ｃ大阪
14      福岡
15      京都
16      鳥栖
17      仙台
18      札幌
19      神戸
20     川崎Ｆ
21      甲府
22    FC東京
23      大分
24      新潟
25      大宮
26      山形
27      水戸
28    横浜FC
29      群馬
30      徳島
31      愛媛
32      熊本
33      岐阜
34      栃木
35      岡山
36      富山
37     北九州
38      鳥取
39      松本
40      町田
41      長崎
42      讃岐
43     相模原
44      長野
45    YS横浜
46      琉球
47      金沢
48      藤枝
49      福島
50      秋田
51      盛岡
52      山口
53     鹿児島
54    Ｃ大23
55    Ｇ大23
56    Ｆ東23
57      沼津
Name: ホーム, dtype: object

In [10]:
# チーム名を変換する辞書を作成
team_df = pd.DataFrame(team_list,columns=["TOTO"])
team_df["公式記録"] = [
    teams[7], #横浜FM
    teams[0], #鹿島
    teams[4], #広島
    teams[5], #清水
    teams[16], #鳥栖
    teams[17], #仙台
    teams[13], #セレッソ
    teams[25], #大宮
    teams[3], #ガンバ
    teams[31], #愛媛
    teams[14], #福岡
    teams[28], #横浜FC
    teams[1], #名古屋
    teams[2], #浦和
    teams[21], #甲府
    teams[22], #FC東京
    teams[10], #磐田
    teams[19], #神戸
    teams[12], #柏
    teams[20], #川崎
    teams[52], #山口
    teams[15], #京都
    teams[18], #札幌
    teams[24], #新潟
    teams[9], #千葉
    teams[8], #ヴェルディ
    teams[47], #金沢
    teams[32], #熊本
    teams[42], #讃岐
    teams[40], #町田
    teams[35], #岡山
    teams[27], #水戸
    teams[11], #湘南
    teams[39], #松本
    teams[26], #山形
    teams[29], #群馬
    teams[34], #栃木
    teams[57], #沼津
    teams[41], #Ｖ・ファーレン長崎
    teams[33], #ＦＣ岐阜
    teams[23], #大分トリニータ
    teams[30], #徳島ヴォルティス
    teams[53], #鹿児島ユナイテッドＦＣ
    teams[50], #ブラウブリッツ秋田
    teams[46], #ＦＣ琉球
    teams[43], #ＳＣ相模原
    teams[36], #カターレ富山
    teams[37], #ギラヴァンツ北九州
    teams[44], #ＡＣ長野パルセイロ
    teams[38], #ガイナーレ鳥取
    teams[49], #福島ユナイテッドＦＣ
    teams[48], #藤枝ＭＹＦＣ
    teams[51], #盛岡
    teams[45] #Ｙ．Ｓ．Ｃ．Ｃ．横浜
  ]
display(team_df)

           TOTO  公式記録
0     横浜 Ｆ・マリノス  横浜FM
1      鹿島アントラーズ    鹿島
2     サンフレッチェ広島    広島
3       清水エスパルス    清水
4         サガン鳥栖    鳥栖
5        ベガルタ仙台    仙台
6        セレッソ大阪   Ｃ大阪
7     大宮アルディージャ    大宮
8         ガンバ大阪   Ｇ大阪
9          愛媛ＦＣ    愛媛
10       アビスパ福岡    福岡
11         横浜ＦＣ  横浜FC
12     名古屋グランパス   名古屋
13        浦和レッズ    浦和
14    ヴァンフォーレ甲府    甲府
15         ＦＣ東京  FC東京
16       ジュビロ磐田    磐田
17      ヴィッセル神戸    神戸
18        柏レイソル     柏
19     川崎フロンターレ   川崎Ｆ
20     レノファ山口ＦＣ    山口
21    京都サンガF.C.    京都
22  北海道コンサドーレ札幌    札幌
23    アルビレックス新潟    新潟
24  ジェフユナイテッド千葉    千葉
25      東京ヴェルディ   東京Ｖ
26      ツエーゲン金沢    金沢
27       ロアッソ熊本    熊本
28     カマタマーレ讃岐    讃岐
29     ＦＣ町田ゼルビア    町田
30     ファジアーノ岡山    岡山
31    水戸ホーリーホック    水戸
32      湘南ベルマーレ    湘南
33       松本山雅ＦＣ    松本
34     モンテディオ山形    山形
35     ザスパクサツ群馬    群馬
36         栃木ＳＣ    栃木
37     アスルクラロ沼津    沼津
38    Ｖ・ファーレン長崎    長崎
39         ＦＣ岐阜    岐阜
40      大分トリニータ    大分
41     徳島ヴォルティス    徳島
42  鹿児島ユナイテッドＦＣ   鹿児島
43    ブラウブリッツ秋田    秋田
44         ＦＣ琉球    琉球
45        ＳＣ相模原   相模原
46       カターレ富山    富山
47    ギラヴァンツ北九州   北九州
48    ＡＣ長野パルセイロ    長野
49      ガイナーレ鳥取    鳥取
50   福島ユナイテッドＦＣ    福島
51       藤枝ＭＹＦＣ    藤枝
52      グルージャ盛岡    盛岡
53   Ｙ．Ｓ．Ｃ．Ｃ．横浜  YS横浜

### スタジアム名変換DB

あんまり変わらない気がするが、合致しないものを抽出してみる。

In [11]:
# 抽出したチーム名を含むデータのみにする
data = data[data["ホーム"].isin(team_list) & data["アウェイ"].isin(team_list)]

In [12]:
studium_list = data["競技場"].drop_duplicates().reset_index(drop=True)
display(studium_list)

0      日産ス
1      カシマ
2      Ｅスタ
3     アイスタ
4     ベアスタ
5     ユアスタ
6     ヤンマー
7     ＮＡＣＫ
8      吹田Ｓ
9     ニンスタ
10    レベスタ
11    ニッパツ
12    パロ瑞穂
13      埼玉
14    中銀スタ
15     味スタ
16     ヤマハ
17    ノエスタ
18       柏
19     等々力
20    維新公園
21     豊田ス
22     西京極
23     札幌ド
24    デンカＳ
25    フクアリ
26    石川西部
27    えがおＳ
28    ピカスタ
29      町田
      ...
35    ＮＤスタ
36    正田スタ
37     栃木グ
38      愛鷹
39     エコパ
40    トラスタ
41     長良川
42     大銀ド
43    鳴門大塚
44    味フィ西
45    札幌厚別
46      鴨池
47    Ａ‐スタ
48    沖縄県陸
49    ギオンス
50     熊谷陸
51     神戸ユ
52      富山
53    ミクスタ
54     長野Ｕ
55    とりスタ
56    とうスタ
57     藤枝サ
58    みらスタ
59    三協Ｆ柏
60     秋田陸
61      下関
62     水前寺
63    いわスタ
64    サンアル
Name: 競技場, Length: 65, dtype: object

In [13]:
# 公式記録のスタジアム名データを作成
studiums = df["スタジアム"].drop_duplicates().reset_index(drop=True)
display(studiums)

0        笠松
1       瑞穂球
2      ＮＡＣＫ
3      ノエスタ
4       広島ス
5        国立
6      アイスタ
7        長崎
8      ＢＭＷス
9       等々力
10      太田陸
11     ニンスタ
12       鴨池
13       千葉
14      草薙陸
15      西京極
16       川越
17     味フィ西
18      Ｃスタ
19      神戸ユ
20       鈴鹿
21     ニッパツ
22      カシマ
23       万博
24       駒場
25      Ｅスタ
26      博多陸
27       市原
28      札幌ド
29      水前寺
       ...
101     三木陸
102     栃木グ
103      津山
104    とりスタ
105    長良川球
106    金鳥スタ
107    中銀スタ
108    トラスタ
109     長崎市
110      大垣
111    ギオンス
112    沖縄県陸
113    石川西部
114     藤枝サ
115    Ａ‐スタ
116      佐久
117    いわスタ
118    沖縄市陸
119    チュスタ
120     あいづ
121    いわきグ
122    維新公園
123     長野Ｕ
124      下関
125     秋田陸
126    魚津桃山
127     吹田Ｓ
128    ミクスタ
129      愛鷹
130      北上
Name: スタジアム, Length: 131, dtype: object

In [14]:
# 公式記録と合わないものを抽出
tmp = data[~data["競技場"].isin(studiums)]
tmp["競技場"].drop_duplicates()

10    みらスタ
4     三協Ｆ柏
9     サンアル
Name: 競技場, dtype: object

恐らく

|TOTO記録の名前|公式記録の名前|備考|
|:-------------|:-------------|:-----|
|みらスタ      |維新公園       |維新みらいふスタジアム|
|三協Ｆ柏      |柏            |三協フロンテア柏スタジアム|
|サンアル      |松本          |サンプロ アルウィン|

っていう感じかと

In [15]:
studium_df = pd.DataFrame()
studium_df["TOTO"] = tmp["競技場"].drop_duplicates()
studium_df["公式記録"] = ["維新公園","柏","松本"]
studium_df = studium_df.reset_index(drop=True)
display(studium_df)

   TOTO  公式記録
0  みらスタ  維新公園
1  三協Ｆ柏     柏
2  サンアル    松本

### DBとして保存し、辞書として利用できるようにする

In [16]:
team_df = team_df.set_index("TOTO",drop=True)

In [17]:
studium_df = studium_df.set_index("TOTO",drop=True)

In [18]:
# DBに保存
import sqlite3
import os
TOTO_DB = "data/toto.db"
if os.path.exists('data') == False:
    os.mkdir('data')
conn = sqlite3.connect(TOTO_DB) # DB接続
team_df.to_sql("team", conn, if_exists='replace') # DFをDBに変換
studium_df.to_sql("studium", conn, if_exists='replace') # DFをDBに変換

In [19]:
import sqlite3
conn = sqlite3.connect(TOTO_DB)
team_df = pd.io.sql.read_sql_query("select * from team",conn)
team_df = team_df.set_index("TOTO",drop=True)
display(team_df)

             公式記録
TOTO
横浜 Ｆ・マリノス    横浜FM
鹿島アントラーズ       鹿島
サンフレッチェ広島      広島
清水エスパルス        清水
サガン鳥栖          鳥栖
ベガルタ仙台         仙台
セレッソ大阪        Ｃ大阪
大宮アルディージャ      大宮
ガンバ大阪         Ｇ大阪
愛媛ＦＣ           愛媛
アビスパ福岡         福岡
横浜ＦＣ         横浜FC
名古屋グランパス      名古屋
浦和レッズ          浦和
ヴァンフォーレ甲府      甲府
ＦＣ東京         FC東京
ジュビロ磐田         磐田
ヴィッセル神戸        神戸
柏レイソル           柏
川崎フロンターレ      川崎Ｆ
レノファ山口ＦＣ       山口
京都サンガF.C.      京都
北海道コンサドーレ札幌    札幌
アルビレックス新潟      新潟
ジェフユナイテッド千葉    千葉
東京ヴェルディ       東京Ｖ
ツエーゲン金沢        金沢
ロアッソ熊本         熊本
カマタマーレ讃岐       讃岐
ＦＣ町田ゼルビア       町田
ファジアーノ岡山       岡山
水戸ホーリーホック      水戸
湘南ベルマーレ        湘南
松本山雅ＦＣ         松本
モンテディオ山形       山形
ザスパクサツ群馬       群馬
栃木ＳＣ           栃木
アスルクラロ沼津       沼津
Ｖ・ファーレン長崎      長崎
ＦＣ岐阜           岐阜
大分トリニータ        大分
徳島ヴォルティス       徳島
鹿児島ユナイテッドＦＣ   鹿児島
ブラウブリッツ秋田      秋田
ＦＣ琉球           琉球
ＳＣ相模原         相模原
カターレ富山         富山
ギラヴァンツ北九州     北九州
ＡＣ長野パルセイロ      長野
ガイナーレ鳥取        鳥取
福島ユナイテッドＦＣ     福島
藤枝ＭＹＦＣ         藤枝
グルージャ盛岡        盛岡
Ｙ．Ｓ．Ｃ．Ｃ．横浜   YS横浜

In [20]:
toto, miniA, miniB, goal = get_toto_schedule(1043)

In [21]:
team_df["公式記録"]["鹿島アントラーズ"]

'鹿島'

In [22]:
studium_df.iloc[0]["公式記録"]

'維新公園'

In [23]:
for i in range(len(toto)):
    toto.iloc[i]["ホーム"] = team_df["公式記録"][toto.iloc[i]["ホーム"]]
    toto.iloc[i]["アウェイ"] = team_df["公式記録"][toto.iloc[i]["アウェイ"]]
    for j in range(len(studium_df)):
        if toto.iloc[i]["競技場"] == studium_df.index[j]:
            toto.iloc[i]["競技場"] = studium_df.iloc[j]["公式記録"]
            break
display(toto)

      開催日 試合開始予定時間   競技場  ホーム  アウェイ
1   09/22    15:00     柏    柏    鳥栖
2   09/22    16:00   ヤマハ   磐田  横浜FM
3   09/22    18:00  トラスタ   長崎    仙台
4   09/22    19:00   等々力  川崎Ｆ   名古屋
5   09/22    19:00   Ｅスタ   広島  FC東京
6   09/22    19:00  ＢＭＷス   湘南   Ｃ大阪
7   09/23    18:00    埼玉   浦和    神戸
8   09/23    19:00   札幌ド   札幌    鹿島
9   09/22    19:00  維新公園   山口    大分
10  09/23    15:00  フクアリ   千葉  横浜FC
11  09/23    14:00   長良川   岐阜   東京Ｖ
12  09/22    16:00    町田   町田    徳島
13  09/22    18:30  中銀スタ   甲府    岡山

In [24]:
import download
toto, miniA, miniB, goal = download.get_toto_schedule(1049)

In [25]:
display(toto, miniA, miniB, goal)

      開催日 試合開始予定時間   競技場   ホーム  アウェイ
1   10/20    14:00  ユアスタ    仙台    鳥栖
2   10/20    14:00  アイスタ    清水    広島
3   10/20    15:00   吹田Ｓ   Ｇ大阪  横浜FM
4   10/20    16:00    埼玉    浦和    鹿島
5   10/20    16:00  ＢＭＷス    湘南    札幌
6   10/20    19:00   味スタ  FC東京   Ｃ大阪
7   10/20    19:00   等々力   川崎Ｆ    神戸
8   10/21    16:00  トラスタ    長崎    磐田
9   10/21    16:00   Ｃスタ    岡山    町田
10  10/20    15:00   西京極    京都    新潟
11  10/21    14:00    松本    松本    岐阜
12  10/21    13:00  ＮＤスタ    山形    福岡
13  10/21    14:00  ピカスタ    讃岐    山口

     開催日 試合開始予定時間   競技場  ホーム  アウェイ
1  10/20    14:00  ユアスタ   仙台    鳥栖
2  10/20    14:00  アイスタ   清水    広島
3  10/20    15:00   吹田Ｓ  Ｇ大阪  横浜FM
4  10/20    16:00    埼玉   浦和    鹿島
5  10/20    16:00  ＢＭＷス   湘南    札幌

     開催日 試合開始予定時間   競技場   ホーム アウェイ
1  10/20    19:00   味スタ  FC東京  Ｃ大阪
2  10/20    19:00   等々力   川崎Ｆ   神戸
3  10/21    16:00  トラスタ    長崎   磐田
4  10/21    16:00   Ｃスタ    岡山   町田
5  10/20    15:00   西京極    京都   新潟

     開催日 試合開始予定時間   競技場  ホーム  アウェイ
1  10/20    14:00  ユアスタ   仙台    鳥栖
2  10/20    15:00   吹田Ｓ  Ｇ大阪  横浜FM
3  10/20    16:00    埼玉   浦和    鹿島

## TOTOの結果を取得する

既に結果が出た開催データに関して、結果も公表されているので取得しておく

In [26]:
url = "http://sport-kuji.toto-dream.com/dci/I/IPB/IPB01.do?op=lnkHoldCntLotResultLsttoto&holdCntId=" + str(1041)
dfs = pd.io.html.read_html(url)
if len(dfs) > 2:
    for i in range(len(dfs)):
        if dfs[i][1][0] == "競技場":
            print("result:",i)
            display(dfs[i])
        if dfs[i][1][0] == "1等":
            print("prize:",i)
            display(dfs[i])
else:
    print("Not held")

result: 2

        0     1      2     3     4    5    6
0     開催日   競技場  予想チーム   NaN   NaN  NaN  NaN
1      No   ホーム   試合結果  アウェイ  くじ結果  NaN  NaN
2   09/08   味スタ      1   東京Ｖ   2-1  横浜Ｃ  1.0
3   09/09   味スタ      2    川崎   1-3   鹿島  2.0
4   09/09  ヤンマー      3   Ｃ大阪   2-2   湘南  0.0
5   09/09  三協Ｆ柏      4     柏   1-1   甲府  0.0
6   09/09   日産ス      5   横浜Ｍ   3-1  Ｇ大阪  1.0
7   09/08  デンカＳ      6    新潟   5-0   岐阜  1.0
8   09/08   西京極      7    京都   0-0   金沢  0.0
9   09/09    町田      8    町田   0-0   水戸  0.0
10  09/09  みらスタ      9    山口   0-1   山形  2.0
11  09/08  レベスタ     10    福岡   0-1   松本  2.0
12  09/08  ニンスタ     11    愛媛   0-0   讃岐  0.0
13  09/08  えがおＳ     12    熊本   1-3   大分  2.0
14  09/09   Ｃスタ     13    岡山   0-2   千葉  2.0

prize: 3

         0            1           2        3
0   第1041回           1等          2等       3等
1     当せん金  35,037,555円  2,502,682円  98,790円
2    当せん口数           1口          3口      76口
3  次回への繰越金           0円          0円       0円

result: 8

       0     1      2     3     4    5    6
0    開催日   競技場  予想チーム   NaN   NaN  NaN  NaN
1     No   ホーム   試合結果  アウェイ  くじ結果  NaN  NaN
2  09/08   味スタ      1   東京Ｖ   2-1  横浜Ｃ  1.0
3  09/09   味スタ      2    川崎   1-3   鹿島  2.0
4  09/09  ヤンマー      3   Ｃ大阪   2-2   湘南  0.0
5  09/09  三協Ｆ柏      4     柏   1-1   甲府  0.0
6  09/09   日産ス      5   横浜Ｍ   3-1  Ｇ大阪  1.0

prize: 9

         0        1
0   第1041回       1等
1     当せん金  25,561円
2    当せん口数     252口
3  次回への繰越金       0円

result: 14

       0     1      2     3     4    5    6
0    開催日   競技場  予想チーム   NaN   NaN  NaN  NaN
1     No   ホーム   試合結果  アウェイ  くじ結果  NaN  NaN
2  09/08  デンカＳ      1    新潟   5-0   岐阜  1.0
3  09/08   西京極      2    京都   0-0   金沢  0.0
4  09/09    町田      3    町田   0-0   水戸  0.0
5  09/09  みらスタ      4    山口   0-1   山形  2.0
6  09/08  レベスタ      5    福岡   0-1   松本  2.0

prize: 15

         0        1
0   第1041回       1等
1     当せん金  21,978円
2    当せん口数     241口
3  次回への繰越金       0円

result: 20

       0     1   2      3    4     5
0    開催日   競技場  No  予想チーム   得点  くじ結果
1  09/08   味スタ   1    東京Ｖ    2     2
2      2   横浜Ｃ   1      1  NaN   NaN
3  09/09   味スタ   3     川崎    1     1
4      4    鹿島   3      3  NaN   NaN
5  09/09  ヤンマー   5    Ｃ大阪    2     2
6      6    湘南   2      2  NaN   NaN

prize: 21

         0         1       2
0   第1041回        1等      2等
1     当せん金  198,063円  5,800円
2    当せん口数       39口    889口
3  次回への繰越金        0円      0円

In [27]:
def _process_result(tmp,hldCnt):
    if len(tmp.columns)==7: # toto/miniのみ。goalは除外
        tmp0 = tmp[2:].rename(columns={0:tmp[0][0],1:tmp[1][0],2:"index",3:tmp[1][1],4:tmp[2][1],5:tmp[3][1],6:tmp[4][1]}).reset_index(drop=True)
        tmp0["開催回"] = hldCnt
        return tmp0
    elif len(tmp.columns)==6:
        return None   # Goalは除外
    else:
        return None
    
_process_result(dfs[2],1041)

      開催日   競技場 index  ホーム 試合結果 アウェイ  くじ結果   開催回
0   09/08   味スタ     1  東京Ｖ  2-1  横浜Ｃ   1.0  1041
1   09/09   味スタ     2   川崎  1-3   鹿島   2.0  1041
2   09/09  ヤンマー     3  Ｃ大阪  2-2   湘南   0.0  1041
3   09/09  三協Ｆ柏     4    柏  1-1   甲府   0.0  1041
4   09/09   日産ス     5  横浜Ｍ  3-1  Ｇ大阪   1.0  1041
5   09/08  デンカＳ     6   新潟  5-0   岐阜   1.0  1041
6   09/08   西京極     7   京都  0-0   金沢   0.0  1041
7   09/09    町田     8   町田  0-0   水戸   0.0  1041
8   09/09  みらスタ     9   山口  0-1   山形   2.0  1041
9   09/08  レベスタ    10   福岡  0-1   松本   2.0  1041
10  09/08  ニンスタ    11   愛媛  0-0   讃岐   0.0  1041
11  09/08  えがおＳ    12   熊本  1-3   大分   2.0  1041
12  09/09   Ｃスタ    13   岡山  0-2   千葉   2.0  1041

当選金に関しては、当選口数や繰越金はあまり重要なデータではないので、

第何回:当選金額

という情報に置き換える。

In [28]:
import re
def _process_prize_frame(tmp):
    hldcnt = re.sub(r"\D","",tmp[0][0])   # 第〇回から数値だけ抽出
    if len(tmp.columns)==4: # TOTO
        tmp0 = tmp[1:].rename(columns={0:"開催回",1:tmp[1][0],2:tmp[2][0],3:tmp[3][0]})
        tmp0["開催回"].iloc[0] = hldcnt
        return tmp0.iloc[0:1].set_index("開催回")
    elif len(tmp.columns)==2: # mini TOTO
        tmp0 = tmp[1:].rename(columns={0:"開催回",1:tmp[1][0]})
        tmp0["開催回"].iloc[0] = hldcnt
        return tmp0.iloc[0:1].set_index("開催回")
    elif len(tmp.columns)==3: # toto GOAL
        tmp0 = tmp[1:].rename(columns={0:"開催回",1:tmp[1][0],2:tmp[2][0]})
        tmp0["開催回"].iloc[0] = hldcnt
        return tmp0.iloc[0:1].set_index("開催回")

_process_prize_frame(dfs[9])

           1等
開催回
1041  25,561円

In [29]:
def get_toto_expection(holdCntId):
    url = "http://sport-kuji.toto-dream.com/dci/I/IPC/IPC01.do?op=initVoteRate&commodityId=01&holdCntId=%04d" % holdCntId
    dfs = pd.io.html.read_html(url)
    if len(dfs) > 2:
        for i in range(len(dfs)):
            if dfs[i][0][0] == "開催日":
                return dfs[i].dropna().rename(columns={4:"予想1",5:"予想0",6:"予想2"}).reset_index()
    return None

def get_miniA_expection(holdCntId):
    url = "http://sport-kuji.toto-dream.com/dci/I/IPC/IPC01.do?op=initVoteRate&commodityId=06&holdCntId=%04d" % holdCntId
    dfs = pd.io.html.read_html(url)
    if len(dfs) > 2:
        for i in range(len(dfs)):
            if dfs[i][0][0] == "開催日":
                return dfs[i].dropna().rename(columns={4:"予想1",5:"予想0",6:"予想2"}).reset_index()
    return None

def get_miniB_expection(holdCntId):
    url = "http://sport-kuji.toto-dream.com/dci/I/IPC/IPC01.do?op=initVoteRate&commodityId=07&holdCntId=%04d" % holdCntId
    dfs = pd.io.html.read_html(url)
    if len(dfs) > 2:
        for i in range(len(dfs)):
            if dfs[i][0][0] == "開催日":
                return dfs[i].dropna().rename(columns={4:"予想1",5:"予想0",6:"予想2"}).reset_index()
    return None


def get_goal_expection(holdCntId):
    url = "http://sport-kuji.toto-dream.com/dci/I/IPC/IPC01.do?op=initVoteRate&commodityId=02&holdCntId=%04d" %holdCntId
    dfs = pd.io.html.read_html(url)
    if len(dfs) > 2:
        for i in range(len(dfs)):
            if dfs[i][0][0] == "開催日":
                return dfs[i].dropna().rename(columns={5:"予想0点",6:"予想1点",7:"予想2点",8:"予想3点以上"}).reset_index()
    return None

get_toto_expection(1041)

,index,0,1,2,3,予想1,予想0,予想2,7
0,2,09/08,18:00,1,東京Ｖ,"305,392（30.51%）","261,031（26.07%）","434,650（43.42%）",横浜Ｃ
1,5,09/09,19:00,2,川崎,"588,430（58.78%）","167,822（16.76%）","244,821（24.46%）",鹿島
2,8,09/09,19:00,3,Ｃ大阪,"614,064（61.34%）","160,470（16.03%）","226,539（22.63%）",湘南
3,11,09/09,19:00,4,柏,"690,050（68.93%）","153,131（15.30%）","157,892（15.77%）",甲府
4,14,09/09,19:00,5,横浜Ｍ,"633,870（63.32%）","161,578（16.14%）","205,625（20.54%）",Ｇ大阪
5,17,09/08,19:00,6,新潟,"442,052（44.16%）","257,632（25.73%）","301,389（30.11%）",岐阜
6,20,09/08,19:00,7,京都,"384,032（38.36%）","251,820（25.16%）","365,221（36.48%）",金沢
7,23,09/09,18:00,8,町田,"738,228（73.74%）","144,693（14.46%）","118,152（11.80%）",水戸
8,26,09/09,19:00,9,山口,"345,755（34.54%）","252,920（25.26%）","402,398（40.20%）",山形
9,29,09/08,18:00,10,福岡,"435,535（43.51%）","237,725（23.75%）","327,813（32.74%）",松本
10,32,09/08,19:00,11,愛媛,"714,716（71.39%）","174,886（17.47%）","111,471（11.14%）",讃岐
11,35,09/08,18:00,12,熊本,"142,889（14.27%）","150,274（15.01%）","707,910（70.72%）",大分
12,38,09/09,18:00,13,岡山,"539,639（53.91%）","172,581（17.24%）","288,853（28.85%）",千葉

In [30]:
def get_toto_result(holdCntId):
    """
    TOTOの対象ゲームを収集
    引数として開催回を指定する
    """
    toto = None
    toto_prize = None
    miniA = None
    miniA_prize = None
    miniB = None
    miniB_prize = None
    goal = None
    goal_prize = None
    url = "http://sport-kuji.toto-dream.com/dci/I/IPB/IPB01.do?op=lnkHoldCntLotResultLsttoto&holdCntId=%04d" % holdCntId
    dfs = pd.io.html.read_html(url)
    for df in dfs:
        if len(df)>=4 and df[1][0]=="競技場":
            if len(df)==15:
                toto = _process_result(df,holdCntId)
                toto_exp = get_toto_expection(holdCntId)
                if toto_exp is not None:
                    toto["予想1"] = toto_exp["予想1"]
                    toto["予想0"] = toto_exp["予想0"]
                    toto["予想2"] = toto_exp["予想2"]
            elif len(df) == 7:
                if miniA is None:
                    miniA = _process_result(df,holdCntId)
                    miniA_exp = get_miniA_expection(holdCntId)
                    if miniA_exp is not None:
                        miniA["予想1"] = miniA_exp["予想1"]
                        miniA["予想0"] = miniA_exp["予想0"]
                        miniA["予想2"] = miniA_exp["予想2"]
                elif miniB is None:
                    miniB = _process_result(df,holdCntId)
                    miniB_exp = get_miniB_expection(holdCntId)
                    if miniB_exp is not None:
                        miniB["予想1"] = miniB_exp["予想1"]
                        miniB["予想0"] = miniB_exp["予想0"]
                        miniB["予想2"] = miniB_exp["予想2"]
                elif goal is None:
                    goal = _process_result(df,holdCntId)
                    goal_exp = get_goal_expection(holdCntId)
                    if goal is not None and goal_exp is not None:
                        goal["予想0点"] = goal_exp["予想0点"]
                        goal["予想1点"] = goal_exp["予想1点"]
                        goal["予想2点"] = goal_exp["予想2点"]
                        goal["予想3点以上"] = goal_exp["予想3点以上"]
        if len(df)>=3 and df[1][0]=="1等":
            if len(df.columns) == 4:
                toto_prize = _process_prize_frame(df)
            elif len(df.columns) == 2:
                if miniA_prize is None:
                    miniA_prize = _process_prize_frame(df)
                else:
                    miniB_prize = _process_prize_frame(df)
            elif len(df.columns) == 3:
                goal_prize = _process_prize_frame(df)
#    return toto, miniA, miniB, goal, toto_prize, miniA_prize, miniB_prize, goal_prize
    return toto, miniA, miniB, toto_prize, miniA_prize, miniB_prize

In [31]:
t, a, b, tp, ap, bp = get_toto_result(1041)

In [32]:
display(t)

,開催日,競技場,index,ホーム,試合結果,アウェイ,くじ結果,開催回,予想1,予想0,予想2
0,09/08,味スタ,1,東京Ｖ,2-1,横浜Ｃ,1.0,1041,"305,392（30.51%）","261,031（26.07%）","434,650（43.42%）"
1,09/09,味スタ,2,川崎,1-3,鹿島,2.0,1041,"588,430（58.78%）","167,822（16.76%）","244,821（24.46%）"
2,09/09,ヤンマー,3,Ｃ大阪,2-2,湘南,0.0,1041,"614,064（61.34%）","160,470（16.03%）","226,539（22.63%）"
3,09/09,三協Ｆ柏,4,柏,1-1,甲府,0.0,1041,"690,050（68.93%）","153,131（15.30%）","157,892（15.77%）"
4,09/09,日産ス,5,横浜Ｍ,3-1,Ｇ大阪,1.0,1041,"633,870（63.32%）","161,578（16.14%）","205,625（20.54%）"
5,09/08,デンカＳ,6,新潟,5-0,岐阜,1.0,1041,"442,052（44.16%）","257,632（25.73%）","301,389（30.11%）"
6,09/08,西京極,7,京都,0-0,金沢,0.0,1041,"384,032（38.36%）","251,820（25.16%）","365,221（36.48%）"
7,09/09,町田,8,町田,0-0,水戸,0.0,1041,"738,228（73.74%）","144,693（14.46%）","118,152（11.80%）"
8,09/09,みらスタ,9,山口,0-1,山形,2.0,1041,"345,755（34.54%）","252,920（25.26%）","402,398（40.20%）"
9,09/08,レベスタ,10,福岡,0-1,松本,2.0,1041,"435,535（43.51%）","237,725（23.75%）","327,813（32.74%）"
10,09/08,ニンスタ,11,愛媛,0-0,讃岐,0.0,1041,"714,716（71.39%）","174,886（17.47%）","111,471（11.14%）"
11,09/08,えがおＳ,12,熊本,1-3,大分,2.0,1041,"142,889（14.27%）","150,274（15.01%）","707,910（70.72%）"
12,09/09,Ｃスタ,13,岡山,0-2,千葉,2.0,1041,"539,639（53.91%）","172,581（17.24%）","288,853（28.85%）"

In [111]:
from tqdm import tqdm_notebook as tqdm
toto_result = pd.DataFrame()
prize = pd.DataFrame()
for i in tqdm(range(198,1052)):
    t, a, b, tp, ap, bp = get_toto_result(i)
    toto_result = toto_result.append(t)
    prize = prize.append(tp)

HBox(children=(IntProgress(value=0, max=854), HTML(value='')))

予想のところが文字列なので、数値に変換しておく。

In [112]:
toto_result["%予想0"] = toto_result["予想0"].str.split("（",expand=True)[1].str.split("%",expand=True)[0].astype("float")
toto_result["%予想1"] = toto_result["予想1"].str.split("（",expand=True)[1].str.split("%",expand=True)[0].astype("float")
toto_result["%予想2"] = toto_result["予想2"].str.split("（",expand=True)[1].str.split("%",expand=True)[0].astype("float")
toto_result["予想0"] = toto_result["予想0"].str.split("（",expand=True)[0].str.replace(",","").fillna("0").astype("int")
toto_result["予想1"] = toto_result["予想1"].str.split("（",expand=True)[0].str.replace(",","").fillna("0").astype("int")
toto_result["予想2"] = toto_result["予想2"].str.split("（",expand=True)[0].str.replace(",","").fillna("0").astype("int")

中止のデータはくじ結果が「中止」もしくは「102」になっているが、これを-1に変更しておく。

In [151]:
toto_result["くじ結果"] = toto_result["くじ結果"].replace("中止", -1)
toto_result["くじ結果"] = toto_result["くじ結果"].replace(102, -1)
display(toto_result[(toto_result["くじ結果"]!=1) & (toto_result["くじ結果"]!=2) & (toto_result["くじ結果"]!=0)])

,index,くじ結果,アウェイ,ホーム,予想0,予想1,予想2,競技場,試合結果,開催回,開催日,%予想0,%予想1,%予想2
2,3,-1.0,札幌,徳島,228271,90339,1058847,鳴門大塚,中止,291,07/14,16.57,6.56,76.87
3,4,-1.0,Ｃ大阪,愛媛,226617,222239,928601,愛媛陸,中止,291,07/14,16.45,16.13,67.42
4,5,-1.0,仙台,福岡,327026,622740,427691,博多球,中止,291,07/14,23.74,45.21,31.05
3,4,-1.0,川崎,鹿島,534172,975754,601007,カシマ,中止,417,09/12,25.31,46.22,28.47
6,7,-1.0,大宮,湘南,526826,299213,1432663,平塚,中止,478,10/30,23.32,13.25,63.43
0,1,-1.0,鹿島,清水,183754,174446,634923,アウスタ,中止,489,03/12,18.50,17.57,63.93
1,2,-1.0,山形,新潟,138010,765923,89190,東北電ス,中止,489,03/12,13.90,77.12,8.98
2,3,-1.0,柏,Ｃ大阪,226996,430968,335159,金鳥スタ,中止,489,03/12,22.86,43.39,33.75
3,4,-1.0,名古屋,仙台,172909,155344,664870,ユアスタ,中止,489,03/12,17.41,15.64,66.95
4,5,-1.0,Ｇ大阪,浦和,161288,195405,636430,埼玉,中止,489,03/12,16.24,19.68,64.08
5,6,-1.0,甲府,福岡,265787,294254,433082,レベスタ,中止,489,03/12,26.76,29.63,43.61
6,7,-1.0,川崎,横浜Ｍ,225128,394240,373755,日産ス,中止,489,03/13,22.67,39.70,37.63
7,8,-1.0,神戸,磐田,222618,565901,204604,ヤマハ,中止,489,03/13,22.42,56.98,20.60
8,9,-1.0,広島,大宮,214465,478219,300439,ＮＡＣＫ,中止,489,03/13,21.60,48.15,30.25
9,10,-1.0,湘南,千葉,188153,586063,218907,フクアリ,中止,489,03/13,18.95,59.01,22.04
10,11,-1.0,Ｆ東京,岡山,80521,79971,832631,カンスタ,中止,489,03/12,8.11,8.05,83.84
11,12,-1.0,熊本,京都,184859,646871,161393,西京極,中止,489,03/13,18.61,65.14,16.25
12,13,-1.0,岐阜,鳥取,273871,269869,449383,とりスタ,中止,489,03/13,27.58,27.17,45.25
0,1,-1.0,福岡,川崎,10287,45335,13342,等々力,中止,491,03/19,14.92,65.74,19.34
1,2,-1.0,名古屋,神戸,14936,19684,34344,ホームズ,中止,491,03/19,21.66,28.54,49.80
2,3,-1.0,仙台,柏,14633,38358,15973,柏,中止,491,03/19,21.22,55.62,23.16
3,4,-1.0,浦和,山形,15272,22328,31364,ＮＤスタ,中止,491,03/19,22.14,32.38,45.48
4,5,-1.0,富山,愛媛,16252,33684,19028,ニンスタ,中止,491,03/19,23.57,48.84,27.59
5,6,-1.0,横浜Ｍ,磐田,17202,26514,25248,ヤマハ,中止,491,03/19,24.94,38.45,36.61
6,7,-1.0,清水,甲府,15154,23302,30508,中銀スタ,中止,491,03/20,21.97,33.79,44.24
7,8,-1.0,Ｃ大阪,広島,16162,27941,24861,広島ビ,中止,491,03/20,23.44,40.51,36.05
8,9,-1.0,新潟,鹿島,14094,38989,15881,カシマ,中止,491,03/20,20.44,56.53,23.03
9,10,-1.0,Ｇ大阪,大宮,14042,20490,34432,ＮＡＣＫ,中止,491,03/20,20.36,29.71,49.93
10,11,-1.0,千葉,札幌,15314,23139,30511,札幌ド,中止,491,03/19,22.21,33.55,44.24
11,12,-1.0,Ｆ東京,岐阜,9630,16812,42522,長良川,中止,491,03/19,13.96,24.38,61.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,10,-1.0,熊本,鳥取,0,0,0,とりスタ,中止,496,04/17,NaN,NaN,NaN
10,11,-1.0,東京Ｖ,栃木,0,0,0,栃木グ,中止,496,04/17,NaN,NaN,NaN
11,12,-1.0,北九州,岐阜,0,0,0,長良川,中止,496,04/17,NaN,NaN,NaN
12,13,-1.0,水戸,愛媛,0,0,0,ニンスタ,中止,496,04/17,NaN,NaN,NaN
10,11,-1.0,福岡,栃木,469132,535528,1002766,栃木グ,中止,564,05/06,23.37,26.68,49.95
12,13,-1.0,京都,徳島,241548,272523,1261348,鳴門大塚,中止,594,09/30,13.61,15.35,71.04
4,5,-1.0,鳥栖,広島,472739,1052085,627159,Ｅスタ,中止,714,08/09,21.97,48.89,29.14
5,6,-1.0,水戸,広島,117700,890629,50565,Ｅスタ,中止,716,08/20,11.12,84.11,4.77
10,11,-1.0,岐阜,群馬,715001,1268386,678578,正田スタ,中止,784,08/01,26.86,47.65,25.49
0,1,-1.0,名古屋,福岡,349885,440121,798828,レベスタ,中止,838,04/16,22.02,27.70,50.28
4,5,-1.0,神戸,鳥栖,396700,543329,648805,ベアスタ,中止,838,04/16,24.97,34.20,40.83
7,8,-1.0,愛媛,金沢,476196,373281,739357,石川西部,中止,838,04/17,29.97,23.49,46.54
9,10,-1.0,水戸,長崎,512302,803675,272857,長崎県立,中止,838,04/17,32.25,50.58,17.17
11,12,-1.0,沼津,相模原,173107,141101,335756,ギオンス,中止,994,03/21,26.63,21.71,51.66
7,8,-1.0,福岡,京都,314389,286166,998181,西京極,中止,1025,07/07,19.66,17.90,62.44
0,1,-1.0,清水,横浜Ｍ,452480,930050,505357,日産ス,中止,1031,07/28,23.97,49.26,26.77
1,2,-1.0,鹿島,Ｇ大阪,352542,400474,1134871,吹田Ｓ,1-1,1031,07/28,18.68,21.21,60.11
2,3,-1.0,柏,神戸,363638,1085855,438394,ノエスタ,1-0,1031,07/28,19.26,57.52,23.22
3,4,-1.0,Ｃ大阪,仙台,489375,627404,771108,ユアスタ,2-2,1031,07/28,25.92,33.23,40.85
4,5,-1.0,川崎,湘南,387927,371457,1128503,ＢＭＷス,中止,1031,07/28,20.55,19.67,59.78
5,6,-1.0,磐田,鳥栖,484625,741260,662002,ベアスタ,0-0,1031,07/28,25.67,39.26,35.07
6,7,-1.0,札幌,名古屋,598607,588606,700674,パロ瑞穂,中止,1031,07/28,31.71,31.18,37.11
7,8,-1.0,浦和,広島,411466,1036744,439677,Ｅスタ,1-4,1031,07/28,21.79,54.92,23.29
8,9,-1.0,金沢,栃木,588954,553929,745004,栃木グ,1-1,1031,07/29,31.20,29.34,39.46
9,10,-1.0,横浜Ｃ,福岡,515973,804906,567008,レベスタ,中止,1031,07/29,27.33,42.64,30.03
10,11,-1.0,山形,讃岐,429561,423446,1034880,ピカスタ,中止,1031,07/29,22.75,22.43,54.82
11,12,-1.0,愛媛,水戸,500107,964902,422878,Ｋｓスタ,4-1,1031,07/29,26.49,51.11,22.40
12,13,-1.0,甲府,松本,337233,1244834,305820,松本,1-0,1031,07/29,17.86,65.94,16.20
7,8,-1.0,湘南,磐田,309464,501148,255190,ヤマハ,中止,1045,09/30,29.04,47.02,23.94
8,9,-1.0,名古屋,Ｃ大阪,216374,495289,354139,ヤンマー,中止,1045,09/30,20.30,46.47,33.23

賞金の方も「円」がついていて文字列扱いなので、数値に変換しておく。

In [ ]:
prize.index = prize.index.astype('int')
prize["1等"] = prize["1等"].str.split("円",expand=True)[0].str.replace(",","").astype("int")
prize["2等"] = prize["2等"].str.split("円",expand=True)[0].str.replace(",","").astype("int")
prize["3等"] = prize["3等"].str.split("円",expand=True)[0].str.replace(",","").astype("int")

In [115]:
#display(prize)

DBに保存しておく。

In [153]:
import sqlite3
import os
TOTO_DB = "data/toto.db"
if os.path.exists('data') == False:
    os.mkdir('data')
conn = sqlite3.connect(TOTO_DB) # DB接続
toto_result.to_sql("toto_result", conn, if_exists='replace',index=False) # DFをDBに変換
prize.to_sql("toto_prize",conn,if_exists="replace")
conn.close()

# TOTOの期待値を計算する

[shir0penk0](https://github.com/shir0penk0)先生の[リポジトリ](https://github.com/shir0penk0/toto)を参考に、期待値を計算してみる。

In [154]:
import download
prize_db = download.get_db_data(data="toto_prize",db_file="toto.db")
toto_result_db = download.get_db_data(data="toto_result", db_file="toto.db")

In [157]:
prize_db

      開催回         1等       2等      3等
0     261    1302082    12329    1230
1     262   56408310   366328   26680
2     263          0   940806   66470
3     264          0   692444   31560
4     265          0  3106094  204350
5     266   46070663   171428   14080
6     268   52189480   237960   16230
7     269   30360925   114166    8150
8     270          0  2194232   81880
9     271    3588163    21817    2090
10    273   20597791   155827   10190
11    274          0   706733   47480
12    275   28963042   203384   21070
13    277   54323710   529113   40420
14    278          0  1616095   95060
15    279    1010659     3708     500
16    280   30798407   216382   19700
17    282    8777903    85522    7260
18    284   11125800    61366    4650
19    286     676318     6983     850
20    288    4176496    31529    2360
21    289   29465170   664662   38380
22    291     224237     2333     300
23    296    5453203    37563    3490
24    297   38569965   183712   12080
25    298   51553425   230052   11960
26    299    6984055    37941    2930
27    300   41296955   157972   12260
28    301          0  2097663   91200
29    303   17035853    75913    5720
..    ...        ...      ...     ...
447   998   39794650  1421126   64120
448  1000          0   446207   22600
449  1002   93402330   693003   55450
450  1004   39629450   303268   33970
451  1005    7688152    78402    6470
452  1006   35172900   198315   14440
453  1008   39083590   492677   36730
454  1010          0   815474   49840
455  1012          0   588764   33860
456  1013          0   358068   14940
457  1015  338737700   502520   27740
458  1018     143121     1740     260
459  1019  100000000   924743   69500
460  1021          0  4081412  313960
461  1025  149406290   244704   22000
462  1027          0   295813   19720
463  1029          0   786216  116470
464  1033   69511977   172125   15880
465  1034   38239285   182068   15550
466  1036    9480878    86495    7870
467  1038   19294205    69486    4540
468  1039    2922310    14970    1460
469  1041   35037555  2502682   98790
470  1042          0  1528735  127400
471  1043   93968630   332216   30120
472  1045    1381595    11669    1140
473  1046          0  4467690  114550
474  1048   27574411   104691    9460
475  1049          0  8227698  152370
476  1051          0  3175307  179740

[477 rows x 4 columns]

In [158]:
prize_db.mean()

開催回    6.455891e+02
1等     2.806263e+07
2等     9.452546e+05
3等     5.597317e+04
dtype: float64